### ISSUE TITLE
Database Fetch Problem

### ISSUE THREAD

**Issue by shubhamsd7** [Kaushallrai/Inventory_Management_System#3]
Data from database is not being fetched.

**Comment by Kaushallrai** [comment]
Fixed the data fetching bug which was caused by the location/path of the files. 
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/8ee9b46e-6380-4dac-abf9-1cd4e4c5fd26)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/51b503d0-7a5c-4261-bdc5-895a7a829170)
