### ISSUE TITLE
Icon not being loaded in Bill

### ISSUE THREAD

**Issue by shubhamsd7** [Kaushallrai/Inventory_Management_System#4]
Please check frontend code. Icon is not being displayed in Bills sections

**Comment by Kaushallrai** [comment]
Fix the issue for icon which was caused by the invalid name of the icon:
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/b3a39055-3739-43fc-864c-0f90b64dae4e)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/f95f7964-0255-47e8-9b99-41a14adf71ed)
