### ISSUE TITLE
inventory not being updated when add or removed items

### ISSUE THREAD

**Issue by nishanmajhi** [Kaushallrai/Inventory_Management_System#6]

**Comment by Kaushallrai** [comment]
Resolved the issue of adding, fetching, and deleting items from the inventory caused by the slow update/XAMPP server error.
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/b16f22d3-b9c4-4b7a-8366-823e4a5653fa)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/8950213b-4db2-4435-9b61-801f1f1aed60)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/156ba8d7-0e92-4301-a612-3398d2fc9e95)
![image](https://github.com/Kaushallrai/Inventory_Management_System/assets/102945888/9845904f-0dd8-4ed3-a642-7f0d5142ec7f)
